#include "registry.h"

void ECSRegistry()
{
	ComponentManager::RegisterComponent<EmptyComponent>(UniqueString("EmptyComponent"));
	ComponentManager::RegisterComponent<VisibilityNotifier2D>(UniqueString("VisibilityNotifier2D"));
	ComponentManager::RegisterComponent<GrassParticles2D>(UniqueString("GrassParticles2D"));
	ComponentManager::RegisterComponent<Spawner2D>(UniqueString("Spawner2D"));
	ComponentManager::RegisterComponent<AnimatedSprite2D>(UniqueString("AnimatedSprite2D"));
	ComponentManager::RegisterComponent<Spring>(UniqueString("Spring"));
	ComponentManager::RegisterComponent<Pearl>(UniqueString("Pearl"));
	ComponentManager::RegisterComponent<Leaf>(UniqueString("Leaf"));
	ComponentManager::RegisterComponent<ParallaxLayer2D>(UniqueString("ParallaxLayer2D"));
	ComponentManager::RegisterComponent<AudioPlayer2D>(UniqueString("AudioPlayer2D"));
	ComponentManager::RegisterComponent<World2D>(UniqueString("World2D"));
	ComponentManager::RegisterComponent<TileMap2D>(UniqueString("TileMap2D"));
	ComponentManager::RegisterComponent<KillArea>(UniqueString("KillArea"));
	ComponentManager::RegisterComponent<ParticleEmitter2D>(UniqueString("ParticleEmitter2D"));
	ComponentManager::RegisterComponent<Gravity2D>(UniqueString("Gravity2D"));
	ComponentManager::RegisterComponent<PhysicsBody2D>(UniqueString("PhysicsBody2D"));
	ComponentManager::RegisterComponent<CollisionBox2D>(UniqueString("CollisionBox2D"));
	ComponentManager::RegisterComponent<CameraController2D>(UniqueString("CameraController2D"));
	ComponentManager::RegisterComponent<PlayerController>(UniqueString("PlayerController"));
	ComponentManager::RegisterComponent<Transform2D>(UniqueString("Transform2D"));
	SystemManager::RegisterSystem<GravitySystem2D>();
	SystemManager::RegisterSystem<PhysicsSystem2D>();
	SystemManager::RegisterSystem<CollisionSystem2D>();
	SystemManager::RegisterSystem<SpawningSystem2D>();
	SystemManager::RegisterSystem<RenderingSystem2D>();
	SystemManager::RegisterSystem<PearlRenderingSystem>();
	SystemManager::RegisterSystem<SpringRenderingSystem>();
	SystemManager::RegisterSystem<LeafRenderingSystem>();
	SystemManager::RegisterSystem<SpriteAnimationSystem2D>();
	SystemManager::RegisterSystem<ParallaxRenderingSystem2D>();
	SystemManager::RegisterSystem<SpringCollisionSystem>();
	SystemManager::RegisterSystem<PlayerLevelTransitionSystem>();
	SystemManager::RegisterSystem<LeafCollisionSystem>();
	SystemManager::RegisterSystem<GrassCollisionSystem>();
	SystemManager::RegisterSystem<PlayerAnimationSystem>();
	SystemManager::RegisterSystem<PlayerControllerSystem>();
	SystemManager::RegisterSystem<KillAreaCollisionSystem>();
	SystemManager::RegisterSystem<ScoreSystem>();
	SystemManager::RegisterSystem<PearlCollisionSystem>();
	SystemManager::RegisterSystem<WorldLeafParticlesSystem>();
	SystemManager::RegisterSystem<GrassParticlesSystem>();
	SystemManager::RegisterSystem<ParticleSystem2D>();
	SystemManager::RegisterSystem<VisibilityNotifingSystem2D>();
	SystemManager::RegisterSystem<TilemapRenderingSystem2D>();
	SystemManager::RegisterSystem<CameraSystem2D>();
}